#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1327811606.202492
__CHEETAH_genTimestamp__ = 'Sat Jan 28 23:33:26 2012'
__CHEETAH_src__ = 'latexTemplate.tmpl'
__CHEETAH_srcLastModified__ = 'Sat Jan 28 23:33:23 2012'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class latexTemplate(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(latexTemplate, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''\\documentclass{article}
\\usepackage{amsmath}
\\begin {document}


\\begin{description}
''')
        for bf in VFSL([locals()]+SL+[globals(), builtin],"bfs",True): # generated from line 7, col 1
            if VFSL([locals()]+SL+[globals(), builtin],"bf.error",True): # generated from line 8, col 2
                write(u'''\t\t''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"bf.error",True) # u'$bf.error' on line 9, col 3
                if _v is not None: write(_filter(_v, rawExpr=u'$bf.error')) # from line 9, col 3.
                write(u'''
''')
                continue
            write(u'''        \\item[''')
            _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"bf",True),"latex",False)() # u'$bf.latex()' on line 12, col 15
            if _v is not None: write(_filter(_v, rawExpr=u'$bf.latex()')) # from line 12, col 15.
            write(u'''] \\hfill \\\\
\t\\begin{tabular}{
''')
            for __i0 in range(len(VFSL([locals()]+SL+[globals(), builtin],"bf.args",True))+1 ): # generated from line 14, col 2
                write(u'''\t|c 
''')
            write(u'''\t|}
\t\\hline

\t''')
            _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"bf",True),"args",True)[0] # u'$bf.args[0]' on line 20, col 2
            if _v is not None: write(_filter(_v, rawExpr=u'$bf.args[0]')) # from line 20, col 2.
            write(u''' ''')
            for arg in VFN(VFSL([locals()]+SL+[globals(), builtin],"bf",True),"args",True)[1:]: # generated from line 21, col 2
                write(u'''\t\t& ''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"arg",True) # u'$arg' on line 22, col 5
                if _v is not None: write(_filter(_v, rawExpr=u'$arg')) # from line 22, col 5.
                write(u''' ''')
            write(u'''\t& ''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"bf.name",True) # u'$bf.name' on line 24, col 4
            if _v is not None: write(_filter(_v, rawExpr=u'$bf.name')) # from line 24, col 4.
            write(u''' \\\\
\t\\hline
''')
            for row in VFN(VFSL([locals()]+SL+[globals(), builtin],"bf",True),"truth_table",False)(): # generated from line 26, col 2
                write(u'''\t\t
\t\t''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"row",True)[0] # u'$row[0]' on line 28, col 3
                if _v is not None: write(_filter(_v, rawExpr=u'$row[0]')) # from line 28, col 3.
                write(u''' ''')
                for val in VFSL([locals()]+SL+[globals(), builtin],"row",True)[1:]: # generated from line 29, col 3
                    write(u'''\t\t\t& ''')
                    _v = VFSL([locals()]+SL+[globals(), builtin],"val",True) # u'$val' on line 30, col 6
                    if _v is not None: write(_filter(_v, rawExpr=u'$val')) # from line 30, col 6.
                    write(u''' ''')
                write(u'''\t\t\\\\
''')
            write(u'''\t\\hline
\t\\end{tabular}
''')
        write(u'''\\end{description}
\\end{document}''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_latexTemplate= 'respond'

## END CLASS DEFINITION

if not hasattr(latexTemplate, '_initCheetahAttributes'):
    templateAPIClass = getattr(latexTemplate, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(latexTemplate)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=latexTemplate()).run()


